version: '3.3'
services:
  web:
    build:
      context: ./bert
      dockerfile: Dockerfile.cpu
    depends_on:
      - db
    env_file:
      - ./bert/.env
    ports:
      - "8000:8000"
    volumes:
      - ./bert:/app
    command: uvicorn main:app --host 0.0.0.0 --reload --reload-dir app

  db:
    image: postgres:latest
    env_file:
      - ./bert/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  test_postgres_data:
