version: '3.3'
services:
  web:
    build:
      context: ./ner
      dockerfile: Dockerfile.gpu
    depends_on:
      - db
    env_file:
      - ./ner/.env
    ports:
      - "8000:8000"
    volumes:
      - ./ner:/app
    command: uvicorn main:app --host 0.0.0.0 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./llm:/app
      - ./data:/data
      - ./models:/models
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.password='sha1:769d24a18487:56942cc9f2d8cabd200f05e2394954dc544262f6'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  db:
    image: postgres:latest
    env_file:
      - ./ner/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  test_postgres_data:
