version: '3.3'
services:
  web:
    build:
      context: ./bert
      dockerfile: Dockerfile.gpu
    depends_on:
      - db
    env_file:
      - ./bert/.env
    ports:
      - "8000:8000"
    volumes:
      - ./bert:/app
    command: uvicorn main:app --host 0.0.0.0 --reload --reload-dir app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./llm:/app
      - ./data:/data
      - ./models:/models
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.password='sha1:769d24a18487:56942cc9f2d8cabd200f05e2394954dc544262f6'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  llamacpp:
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    ports:
      - "8001:8001"
    volumes:
      - ./models:/models
    environment:
      LLAMA_ARG_MODEL: /models/DeepSeek-R1-Distill-Llama-8B-Q8_0.gguf
      LLAMA_ARG_CTX_SIZE: 8192
      LLAMA_ARG_N_PARALLEL: 2
      LLAMA_ARG_ENDPOINT_METRICS: 1
      LLAMA_ARG_PORT: 8001
      LLAMA_ARG_N_GPU_LAYERS: 99
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  db:
    image: postgres:latest
    env_file:
      - ./bert/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  test_postgres_data:
